// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACILwEfGm-JPSHSeSfx4NTiaRHrsb6Uj8',
    appId: '1:35491137537:web:ac10046a652cfe7a421800',
    messagingSenderId: '35491137537',
    projectId: 'student-reminder-4892c',
    authDomain: 'student-reminder-4892c.firebaseapp.com',
    storageBucket: 'student-reminder-4892c.firebasestorage.app',
    measurementId: 'G-9L327FH1WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyME-fEqcJ5qQrAqCbOWIrVtAZ9ri36RI',
    appId: '1:35491137537:android:9d9321d4a808090b421800',
    messagingSenderId: '35491137537',
    projectId: 'student-reminder-4892c',
    storageBucket: 'student-reminder-4892c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcysufYPDhr1PRFUiLQ5Nem_hCsZusJms',
    appId: '1:35491137537:ios:c50857bbf7fc8ba2421800',
    messagingSenderId: '35491137537',
    projectId: 'student-reminder-4892c',
    storageBucket: 'student-reminder-4892c.firebasestorage.app',
    iosBundleId: 'com.example.studentsReminder',
  );

}